export const fields = [
  { header: 'Entry Date', field: 'entryDate' },
  { header: 'Facility', field: 'facility' },
  { header: 'Unique ART Number', field: 'uniqueARTNumber' },
  { header: 'ART Start Date', field: 'ARTStartDate' },
  { header: 'Sex', field: 'sex' },
  { header: 'Age', field: 'age' },
  { header: 'Phone Number', field: 'phoneNumber' },
  { header: 'Regimen', field: 'regimen' },
  { header: 'Start/ Transition Date', field: 'regimenStartTransDate' },
  { header: 'Pregnant/Breastfeeding', field: 'pmtct' },
  { header: 'PMTCT Enrollment Start Date', field: 'pmtctEnrollStartDate' },
  { header: 'High Viral Load', field: 'hvl' },
  { header: 'EAC-3 Completed', field: 'eac3Completed' },
  { header: 'EAC-3 Completion Date', field: 'eac3CompletionDate' },
  { header: 'Pending Status', field: 'pendingStatus' },
  { header: 'Pending Status Date', field: 'pendingStatusDate' },
  { header: 'Eligibility', field: 'eligibility' },
  { header: 'IIT Status', field: 'iit' },
];
