export const regimens = [
  {
    code: '1A',
    regimen: 'AZT/3TC + EFV',
    category: 'TLE',
    ageCategory: '1st Line Adult',
  },
  {
    code: '1B',
    regimen: 'AZT/3TC/NVP',
    category: 'TLE',
    ageCategory: '1st Line Adult',
  },
  {
    code: '1F',
    regimen: 'TDF/3TC/EFV',
    category: 'TLE',
    ageCategory: '1st Line Adult',
  },
  {
    code: '1G',
    regimen: 'TDF/3TC + NVP',
    category: 'TLE',
    ageCategory: '1st Line Adult',
  },
  {
    code: '1H',
    regimen: 'TDF/FTC/ EFV',
    category: 'TLE',
    ageCategory: '1st Line Adult',
  },
  {
    code: '1J',
    regimen: 'TDF/FTC + NVP ',
    category: 'TLE',
    ageCategory: '1st Line Adult',
  },
  {
    code: '2C',
    regimen: 'TDF+3TC + LPV/r',
    category: 'TLE',
    ageCategory: '2nd Line Adult',
  },
  {
    code: '2D',
    regimen: 'TDF/3TC + ATV/r',
    category: 'TLE',
    ageCategory: '2nd Line Adult',
  },
  {
    code: '2E',
    regimen: 'TDF/FTC + LPV/r',
    category: 'TLE',
    ageCategory: '2nd Line Adult',
  },
  {
    code: '2F',
    regimen: 'TDF/FTC + ATV/r',
    category: 'TLE',
    ageCategory: '2nd Line Adult',
  },
  {
    code: '2G',
    regimen: 'AZT/3TC + LPV/r',
    category: 'TLE',
    ageCategory: '2nd Line Adult',
  },
  {
    code: '2H',
    regimen: 'AZT/3TC + ATV/r',
    category: 'TLE',
    ageCategory: '2nd Line Adult',
  },
  {
    code: '2I',
    regimen: 'ABC/3TC + LPV/r',
    category: 'TLE',
    ageCategory: '2nd Line Adult',
  },
  {
    code: '2J',
    regimen: 'ABC/3TC + ATV/r',
    category: 'TLE',
    ageCategory: '2nd Line Adult',
  },
  {
    code: '4A',
    regimen: 'AZT/3TC/NVP',
    category: 'TLE',
    ageCategory: '1st Line Children',
  },
  {
    code: '4B',
    regimen: 'AZT/3TC + EFV',
    category: 'TLE',
    ageCategory: '1st Line Children',
  },
  {
    code: '4C',
    regimen: 'ABC/3TC (120/60) + LPV/r',
    category: 'TLE',
    ageCategory: '1st Line Children',
  },
  {
    code: '4F',
    regimen: 'ABC/3TC + NVP',
    category: 'TLE',
    ageCategory: '1st Line Children',
  },
  {
    code: '4G',
    regimen: 'ABC/3TC (120/60) + EFV (200mg)',
    category: 'TLE',
    ageCategory: '1st Line Children',
  },
  {
    code: '4H',
    regimen: 'TDF/3TC/EFV',
    category: 'TLE',
    ageCategory: '1st Line Children',
  },
  {
    code: '4I',
    regimen: 'ABC/3TC + LPV/r',
    category: 'TLE',
    ageCategory: '1st Line Children',
  },
  {
    code: '4J',
    regimen: 'AZT/3TC (60/30) + LPV/r',
    category: 'TLE',
    ageCategory: '1st Line Children',
  },
  {
    code: '4K',
    regimen: 'TDF/3TC + NVP',
    category: 'TLE',
    ageCategory: '1st Line Children',
  },
  {
    code: '4L',
    regimen: 'ABC/3TC + AZT',
    category: 'TLE',
    ageCategory: '1st Line Children',
  },
  {
    code: '5A',
    regimen: 'AZT/3TC+LPV/r',
    category: 'TLE',
    ageCategory: '2nd Line Children',
  },
  {
    code: '5B',
    regimen: 'AZT/3TC + RAL',
    category: 'TLE',
    ageCategory: '2nd Line Children',
  },
  {
    code: '5C',
    regimen: 'ABC/3TC (120/60) + RAL',
    category: 'TLE',
    ageCategory: '2nd Line Children',
  },
  {
    code: '5D',
    regimen: 'AZT/3TC + ATV/r',
    category: 'TLE',
    ageCategory: '2nd Line Children',
  },
  {
    code: '5E',
    regimen: 'ABC/3TC + ATV/r',
    category: 'TLE',
    ageCategory: '2nd Line Children',
  },
  {
    code: '5F',
    regimen: 'TDF/ 3TC + ATV/r',
    category: 'TLE',
    ageCategory: '2nd Line Children',
  },
  {
    code: '5I',
    regimen: 'ABC/3TC + LPV/r',
    category: 'TLE',
    ageCategory: '2nd Line Children',
  },
  {
    code: '1C',
    regimen: 'TDF/3TC/DTG',
    category: 'TLD',
    ageCategory: '1st Line Adult',
  },
  {
    code: '1D',
    regimen: 'ABC/3TC (600/300) /DTG',
    category: 'TLD',
    ageCategory: '1st Line Adult',
  },
  {
    code: '1E',
    regimen: 'AZT/3TC + DTG',
    category: 'TLD',
    ageCategory: '1st Line Adult',
  },
  {
    code: '2A',
    regimen: 'AZT/3TC + DTG',
    category: 'TLD',
    ageCategory: '2nd Line Adult',
  },
  {
    code: '2B',
    regimen: 'ABC/3TC + DTG',
    category: 'TLD',
    ageCategory: '2nd Line Adult',
  },
  {
    code: '2K',
    regimen: 'TDF/3TC/DTG',
    category: 'TLD',
    ageCategory: '2nd Line Adult',
  },
  {
    code: '4D',
    regimen: 'ABC/3TC (120/60) + DTG',
    category: 'TLD',
    ageCategory: '1st Line Children',
  },
  {
    code: '5G',
    regimen: 'AZT/3TC + DTG',
    category: 'TLD',
    ageCategory: '2nd Line Children',
  },
  {
    code: '5H',
    regimen: 'ABC/3TC + DTG*',
    category: 'TLD',
    ageCategory: '2nd Line Children',
  },
];
